# **Padhai - OneFourthLabs - Data Science (Pandas)**

In [76]:
import numpy as np
import pandas as pd
import seaborn as sns
import random
pi = np.pi

In [77]:
from google.colab import drive
drive.mount('/content/drive')
# !cat drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Pandas/Dataset_files/nifty-200623-235920.csv

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Task 1 : collect diameters and mass for each planet in solar system and compute the density

In [ ]:
mass = pd.Series (
                  data = (0.330, 4.87, 5.97, 0.073, 0.642, 1898, 568, 86.8, 102, 0.0146) , 
                  index = ('MERCURY','VENUS','EARTH','MOON','MARS','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO' )
                 )
mass['PlanetX'] = 6
mass_in_kg = mass * (10**24)

In [ ]:
diameter = pd.Series (
                  data = (4879, 12104,	12756,	3475,	6792,	142984,	120536,	51118,	49528,	2370) , 
                  index = ('MERCURY','VENUS','EARTH','MOON','MARS','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO' )
                 )

radius = diameter/2

In [ ]:
radius

MERCURY     2439.5
VENUS       6052.0
EARTH       6378.0
MOON        1737.5
MARS        3396.0
JUPITER    71492.0
SATURN     60268.0
URANUS     25559.0
NEPTUNE    24764.0
PLUTO       1185.0
dtype: float64

In [ ]:
volume = (4/3) * pi * (radius**3)

In [ ]:
density = mass_in_kg/volume

In [ ]:
density # kg/km3

EARTH      5.49329e+12
JUPITER    1.24004e+12
MARS        3.9133e+12
MERCURY    5.42654e+12
MOON       3.32246e+12
NEPTUNE    1.60343e+12
PLUTO      2.09464e+12
PlanetX            NaN
SATURN      6.1944e+11
URANUS     1.24108e+12
VENUS      5.24498e+12
dtype: object

### Task 2 : Replace all the NaNs with dataset mean

In [ ]:
density_mean = np.mean(density)
print(density_mean)

3019918757082.1875

In [ ]:
density.fillna(density_mean)

EARTH      5.493286e+12
JUPITER    1.240039e+12
MARS       3.913302e+12
MERCURY    5.426538e+12
MOON       3.322460e+12
NEPTUNE    1.603427e+12
PLUTO      2.094639e+12
PlanetX    3.019919e+12
SATURN     6.194402e+11
URANUS     1.241079e+12
VENUS      5.244977e+12
dtype: float64

### Task 3 : Compare Dictionaries with series :
- a. checking if a key is present
- b. summing values
- c. computing std deviation

In [ ]:
# creating a dictionary
%%time
dict_data = {}
N = 100000
for i in range(N):
  dict_data[i] = i%10

CPU times: user 14.7 ms, sys: 6.72 ms, total: 21.5 ms
Wall time: 23.3 ms

In [ ]:
# creating a Series
%%time
series_data = pd.Series(dict_data)

CPU times: user 116 ms, sys: 14.9 ms, total: 131 ms
Wall time: 133 ms

a - checking if a key is present

In [ ]:
#a -  checking if a key is present in dict
%%time
random_int = random.randint(0,N)
print('random_int',random_int)
if random_int in dict_data.keys() : print ('found')
else : print('not found')

random_int 93183
found
CPU times: user 0 ns, sys: 837 µs, total: 837 µs
Wall time: 873 µs

In [ ]:
#a -  checking if a key is present in series
%%time
random_int = random. randint(0,N)
print('random_int',random_int)
if random_int in series_data.index : print ('found')
else : print('not found')

random_int 22655
found
CPU times: user 3.63 ms, sys: 0 ns, total: 3.63 ms
Wall time: 3.83 ms

b - summing values

In [ ]:
#b - summing values in dict
%%time
sum = 0
for value in dict_data.values():
  sum = sum + value
print(sum)

450000
CPU times: user 19.2 ms, sys: 0 ns, total: 19.2 ms
Wall time: 20.5 ms

In [ ]:
#b - summing values in series
%%time
sum = 0
sum = np.sum(series_data)

CPU times: user 596 µs, sys: 137 µs, total: 733 µs
Wall time: 781 µs

c : computing standard deviation

In [ ]:
#c - Computing standard_deviation in dictionary
%%time
sum = 0
for value in dict_data.values():
  sum = sum + value
print(sum)
mean = sum / len(dict_data.keys())
variance = 0
print('mean',mean)
deviation = {}
for key in dict_data.keys() :
  deviation[key] = dict_data[key] - mean
  variance = variance + (deviation[key]**2)
variance = variance /(len(dict_data.keys()) -1)
std_deviation_dict = (variance)**0.5

450000
mean 4.5
CPU times: user 56.3 ms, sys: 4.02 ms, total: 60.3 ms
Wall time: 63 ms

In [ ]:
std_deviation_dict

2.8722956847833423

In [ ]:
#c - Computing standard_deviation in series
%%time
std_deviation_series = np.power(( np.sum( np.power((series_data - np.mean(series_data)),2) ) ) / (np.size(series_data) -1),0.5)

CPU times: user 6.03 ms, sys: 0 ns, total: 6.03 ms
Wall time: 7.55 ms

In [ ]:
std_deviation_series

2.8722956847833423

In [ ]:
%%time
np.std(series_data)

CPU times: user 1.15 ms, sys: 57 µs, total: 1.2 ms
Wall time: 870 µs

2.8722813232690143

#NIFTY case study

In [ ]:
nifty = pd.read_csv('drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Pandas/Dataset_files/nifty-200623-235920.csv',index_col = 0).iloc[:,0]

In [ ]:
nifty

##**Tasks**
### 1. Compute Moving average for last 5 days
### 2. Subset the data to include only friday data

1. Computing moving average for last 5 days

In [ ]:
mean = np.mean(nifty)
moving_average = (nifty.values[0:-4] + nifty.values[1:-3] + nifty.values[2:-2] + nifty.values[3:-1] + nifty.values[4:])/5
# refer below for correct answer

In [ ]:
moving_average

In [ ]:
#1. moving average correct answer
index_cols = pd.to_datetime(pd.Series(nifty.index))
nifty_v2 = pd.Series(data = nifty, index = index_cols)
moving_average = nifty_v2.rolling('5d').mean()

2. Subset the data to include only friday data

In [ ]:
index_cols = pd.to_datetime(pd.Series(nifty.index))
nifty_v2 = pd.Series(data = nifty, index = index_cols)

In [ ]:
Nifty_on_friday = nifty_v2[ nifty_v2.index.weekday == 4 ]
# this solution is better than what instructor did

#DataFrames

###Task 1 : Function to accept nrows and ncolumns return a dataframe of that dimenion having 
column names as : c1, c2, c3 etc.

Row names as : r1, r2, r3 etc

In [ ]:
nrows = 10
rownames = pd.Series(np.arange(1,nrows))

In [ ]:
rownames = list(map(lambda x : str(x) + 'r', rownames ))

In [ ]:
def create_df(nrows,ncols):
  row_names = pd.Series(np.arange(1,nrows+1))
  row_names = list(map(lambda x : 'r' + str(x) , row_names ))

  col_names = pd.Series(np.arange(1,ncols+1))
  col_names = list(map(lambda x : 'c' + str(x), col_names ))
  print(row_names)
  print(col_names)
  df = pd.DataFrame(np.random.randint(1,nrows*ncols, (nrows,ncols)) )
  df.index = row_names
  df.columns = col_names
  return df

In [ ]:
create_df(5,5)

In [ ]:
%%time
create_df(25,250)

In [ ]:
planets = pd.DataFrame({'Mass':mass,'Diameter':diameter})

In [ ]:
planets

In [ ]:
planets.loc['mean'] = ( np.mean(planets['Mass']), np.mean(planets['Diameter']))

In [ ]:
planets

#Using seaborn library for loading datasets..

In [ ]:
planets_sns = sns.load_dataset("planets")

In [ ]:
planets_sns.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

###go through each row of the dataframe and delete it if any of the columns is null

In [ ]:
planets_sns_ = planets_sns.dropna()

In [ ]:
planets_sns_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 498 entries, 0 to 784
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          498 non-null    object
 1   number          498 non-null    int64
 2   orbital_period  498 non-null    float64
 3   mass            498 non-null    float64
 4   distance        498 non-null    float64
 5   year            498 non-null    int64
dtypes: float64(3), int64(2), object(1)
memory usage: 27.2+ KB

In [ ]:
planets_sns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

###Filter and show only those rows which have planets found in 2010-2020 and method is in ('radial velocity','transit') and distance is large(>75 percentile)

In [ ]:
%%time
planets_sns_ = planets_sns.loc[
                               (planets_sns['distance'] >  planets_sns.quantile(0.75)['distance']) & 
                               (planets_sns['method'].isin(['Radial Velocity','Transit'])) & 
                               (planets_sns['year'] >= 2010)
                              ]

CPU times: user 5.1 ms, sys: 0 ns, total: 5.1 ms
Wall time: 6.87 ms

In [ ]:
planets_sns_.describe()

           number  orbital_period       mass     distance         year
count  154.000000      154.000000   7.000000   154.000000   154.000000
mean     2.045455       55.483100   5.207143   654.435649  2011.448052
std      1.834103      159.178501   3.891918   527.480906     1.078865
min      1.000000        0.742960   1.250000   180.000000  2010.000000
25%      1.000000        3.276083   2.450000   303.000000  2011.000000
50%      1.000000        4.641130   4.000000   429.000000  2011.000000
75%      2.000000       16.228912   7.600000   800.000000  2012.000000
max      7.000000     1022.000000  11.100000  3200.000000  2014.000000

###modify the method column to have only the abbreviation of each method

In [ ]:
def abbreviate(string_a):
  return "".join(list((abbr[0] for abbr in string_a.split()))).upper()

In [ ]:
print(abbreviate('my name is Abhijit patra'))

MNIAP

In [ ]:
#planets_sns.method.replace( abbreviate() ,inplace = False)
#planets_sns.method.replace('Transit','T',inplace = True)
#map(abbreviate , planets_sns.method)

planets_sns['short_method'] = planets_sns.method.apply(abbreviate)

In [ ]:
planets_sns

               method  number  orbital_period  ...  distance  year  short_method
0     Radial Velocity       1      269.300000  ...     77.40  2006            RV
1     Radial Velocity       1      874.774000  ...     56.95  2008            RV
2     Radial Velocity       1      763.000000  ...     19.84  2011            RV
3     Radial Velocity       1      326.030000  ...    110.62  2007            RV
4     Radial Velocity       1      516.220000  ...    119.47  2009            RV
...               ...     ...             ...  ...       ...   ...           ...
1030          Transit       1        3.941507  ...    172.00  2006             T
1031          Transit       1        2.615864  ...    148.00  2007             T
1032          Transit       1        3.191524  ...    174.00  2007             T
1033          Transit       1        4.125083  ...    293.00  2008             T
1034          Transit       1        4.187757  ...    260.00  2008             T

[1035 rows x 7 columns]

###How many planets have been discovered per each method type

In [ ]:
planets_sns_gr = planets_sns[planets_sns['year'] >= 2010].groupby('method')

In [ ]:
planets_sns_fraction = planets_sns.groupby('method').count() / planets_sns_gr.count()

###Find out what fraction of planets have been found in the last decade, across each method type

In [ ]:
%%time
planets_sns_fraction

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 9.78 µs

                                 number  orbital_period  ...      year  short_method
method                                                   ...
Astrometry                     1.000000        1.000000  ...  1.000000      1.000000
Eclipse Timing Variations      1.500000        1.500000  ...  1.500000      1.500000
Imaging                        2.111111        4.000000  ...  2.111111      2.111111
Microlensing                   1.769231        3.500000  ...  1.769231      1.769231
Orbital Brightness Modulation  1.000000        1.000000  ...  1.000000      1.000000
Pulsar Timing                  5.000000        5.000000  ...  5.000000      5.000000
Pulsation Timing Variations         NaN             NaN  ...       NaN           NaN
Radial Velocity                2.572093        2.572093  ...  2.572093      2.572093
Transit                        1.185075        1.185075  ...  1.185075      1.185075
Transit Timing Variations      1.000000        1.000000  ...  1.000000      1.000000

[10 rows x 6 columns]

###Nifty Dataset uploaded from drive

In [ ]:
nifty_2 = pd.read_csv('drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Pandas/Dataset_files/FINAL_FROM_DF_nifty.csv',index_col='SYMBOL')

In [ ]:
nifty_2

##Tasks on Nifty datasets

In [ ]:
#import all the given nifty datasets
nifty50_2018 = pd.read_csv('drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Pandas/Dataset_files/Nifty_csv_files_padhai/NIFTY50_2018.csv',index_col = 0)
nifty50_2019 = pd.read_csv('drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Pandas/Dataset_files/Nifty_csv_files_padhai/NIFTY50_2019.csv',index_col = 0)
niftyNext50_2019 = pd.read_csv('drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Pandas/Dataset_files/Nifty_csv_files_padhai/NIFTYNext50_2019.csv',index_col = 0)

In [ ]:
nifty50 = pd.concat([nifty50_2018,nifty50_2019])

###Task 1 : in 2019 , in how many days nifty data was volatile(high > 105% of low)

In [ ]:
nifty50['Volatile'] = nifty50['High'] > nifty50['Low'] * 1.05

In [ ]:
index_cols = pd.to_datetime(nifty50.index)
nifty50.index = index_cols

In [ ]:
nifty50[ (nifty50['Volatile'] == True) & (nifty50.index.year == 2019)]

               Open     High      Low    Close  Volatile
Date
2019-09-20  10746.8  11381.9  10691.0  11274.2      True

###Task 2 : in 2019 , in how many days niftynext50 data was volatile(high > 105% of low)

In [ ]:
niftyNext50_2019['Volatile'] = niftyNext50_2019['High'] > niftyNext50_2019['Low'] * 1.05 
index_cols = pd.to_datetime(niftyNext50_2019.index)
niftyNext50_2019.index = index_cols

In [ ]:
niftyNext50_2019[ (niftyNext50_2019['Volatile'] == True) & (niftyNext50_2019.index.year == 2019)]

                Open      High       Low     Close  Volatile
Date
2019-09-20  26026.45  27476.35  25812.05  27406.85      True

###Task 3 : in 2019 how many days belong to the 4 classes, in essense of -
1. Volatile nifty 50
2. Non volatile nifty 50
3. volatile nifty next 50
4. Non volatile nifty next 50

In [ ]:
nifty50_2019['Volatile'] = nifty50_2019['High'] > nifty50_2019['Low'] * 1.05 
index_cols = pd.to_datetime(nifty50_2019.index)
nifty50_2019.index = index_cols

In [126]:
nifty_2019_groupbed = pd.concat([nifty50_2019.groupby('Volatile').count(),niftyNext50_2019.groupby('Volatile').count()], axis = 1, keys=['nifty50','niftyNext50'])

In [127]:
nifty_2019_groupbed

         nifty50                 niftyNext50
            Open High  Low Close        Open High  Low Close
Volatile
False        244  244  244   244         244  244  244   244
True           1    1    1     1           1    1    1     1

###Task 4 : Calculate mean,median,std for closing values for each weekday in nifty 2019

In [114]:
nifty50_2019[nifty50_2019.index.weekday.isin([0,1,2,3,4])]['Close'].describe()

count      244.000000
mean     11431.835041
std        454.976464
min      10604.350000
25%      11001.625000
50%      11505.650000
75%      11842.100000
max      12271.800000
Name: Close, dtype: float64

###Task 5 : Calculate mean,median,std for closing values for each month in nifty 2019

In [121]:
nifty_mean = nifty50_2019.groupby(pd.Grouper(freq="M")).mean()
nifty_std = nifty50_2019.groupby(pd.Grouper(freq="M")).std()
nifty_median = nifty50_2019.groupby(pd.Grouper(freq="M")).median()

###Task 6 : On the days in which nifty50 closed higher than open, what was the mean of open-close for nifty_next_50

In [128]:
#nifty_2019 = pd.concat([nifty50_2019,niftyNext50_2019], axis = 1, keys=['nifty50','niftyNext50'])

In [139]:
niftyNext50_2019[ nifty50_2019['Close'] > nifty50_2019['Open']].describe()

               Open          High           Low         Close
count    106.000000    106.000000    106.000000    106.000000
mean   27213.883491  27416.519340  27091.969340  27332.585377
std      939.921156    903.124999    967.816771    891.848079
min    25081.400000  25418.000000  24873.250000  25345.100000
25%    26403.512500  26651.962500  26254.712500  26563.750000
50%    27439.075000  27622.025000  27335.675000  27560.475000
75%    28069.412500  28174.037500  27945.300000  28105.625000
max    28794.250000  28953.700000  28671.050000  28765.600000

###Task 7 : In 2019, how many days high lower than previous day's low in nifty50

In [145]:
nifty50_2019_sub = nifty50.iloc[1:].values - nifty50.iloc[:-1].values

In [154]:
nifty50_2019_sub = nifty50_2019_sub[nifty50_2019_sub > 0]

In [155]:
np.shape(nifty50_2019_sub)

(908,)

###Task 8 : in 2019 , in how many days , did the days close exceed the 30 day moving average in NIFTY50(exclude first month)

In [ ]:
nifty50_2019

In [167]:
monthly_rolling = nifty50_2019['Close'].rolling('30d').mean()

In [169]:
nifty50_2019['monthly_moving_average'] = monthly_rolling

In [172]:
nifty50_2019[ nifty50_2019['Close'] > nifty50_2019['monthly_moving_average'] ]

                Open      High  ...  Volatile  monthly_moving_average
Date                            ...
2019-12-30  12274.90  12286.45  ...     False            12212.150000
2019-12-27  12172.90  12258.45  ...     False            12223.366667
2019-12-24  12269.25  12283.70  ...     False            12202.240000
2019-12-23  12235.45  12287.15  ...     False            12212.325000
2019-12-20  12266.45  12293.90  ...     False            12220.821429
...              ...       ...  ...       ...                     ...
2019-01-18  10914.85  10928.20  ...     False            10849.995238
2019-01-17  10920.85  10930.65  ...     False            10852.504545
2019-01-16  10899.65  10928.15  ...     False            10860.045455
2019-01-15  10777.55  10896.95  ...     False            10866.443182
2019-01-01  10881.70  10923.60  ...     False            10808.486364

[100 rows x 6 columns]